"use client";
import { FormEvent, useState } from "react";
const projectTypes=["Editorial","Campaign","Commercial","Beauty","Lifestyle","Event"];
const budgetRanges=["Under $2,000","$2,000–$5,000","$5,000–$10,000","$10,000+","To be discussed"];
export default function BookingCTA({acceptingBookings=true,contactEmail}:{acceptingBookings?:boolean;contactEmail?:string|null}){
 const [status,setStatus]=useState<"idle"|"sending"|"success"|"error">("idle"); const [error,setError]=useState(""); const [type,setType]=useState(""); const [budget,setBudget]=useState("");
 if(!acceptingBookings)return <section id="booking" className="studio-booking studio-booking-closed"><div className="studio-shell"><p className="studio-label">05 / Booking</p><h2>Currently<br /><em>unavailable.</em></h2>{contactEmail&&<a href={`mailto:${contactEmail}`}>General inquiries ↗</a>}</div></section>;
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setStatus("sending");setError("");try{const form=e.currentTarget;const response=await fetch("/api/bookings",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(Object.fromEntries(new FormData(form).entries()))});const result=await response.json();if(!response.ok){setError(result.error||"Please try again.");setStatus("error");return;}form.reset();setType("");setBudget("");setStatus("success");}catch{setError("Unable to send your request right now.");setStatus("error");}}
 return <section id="booking" className="studio-booking"><div className="studio-shell"><div className="studio-booking-head"><div><p className="studio-label">05 / Booking</p><h2>Make it<br /><em>memorable.</em></h2></div><p>Tell me what you're creating, where and when. I'll come back with availability and next steps.</p></div><form onSubmit={submit} className="studio-form"><div className="studio-form-grid">{[["Name","name","text","Your name"],["Email","email","email","you@example.com"],["Company / brand","company","text","Company or agency"],["Production location","location","text","City / country"]].map(([label,name,type,input])=><label key={name}><span>{label}</span><input name={name} type={type} required={name==="name"||name==="email"} placeholder={input}/></label>)}</div><div className="studio-form-row"><div><span>Project type</span><div className="studio-options">{projectTypes.map(x=><button type="button" key={x} className={type===x?"selected":""} onClick={()=>setType(x)}>{x}</button>)}</div><input type="hidden" name="bookingType" value={type}/></div><label><span>Budget range</span><select name="budget" value={budget} onChange={e=>setBudget(e.target.value)}><option value="">Select range</option>{budgetRanges.map(x=><option key={x}>{x}</option>)}</select></label></div><div className="studio-form-grid"><label><span>Preferred date</span><input name="preferredDate" type="date"/></label><label><span>Usage / campaign scope</span><input name="usageRights" placeholder="Web, social, print, paid media…"/></label></div><label><span>Tell me about the project</span><textarea name="message" required minLength={10} rows={5} placeholder="Dates, deliverables, creative direction, usage…"/></label><div className="studio-form-submit"><small>Final rates and usage are confirmed separately.</small><button disabled={status==="sending"}>{status==="sending"?"Sending…":"Send inquiry ↗"}</button></div>{status==="success"&&<p className="studio-form-success">Request received. Thank you — I'll be in touch soon.</p>}{status==="error"&&<p className="studio-form-error">{error}</p>}</form></div></section>;
}
