 "use client";
import {useState} from "react";import {supabaseBrowser} from "@/lib/supabase-browser";import {useRouter} from "next/navigation";
export default function DashboardClient({user,media,bookings,profile}:any){const [tab,setTab]=useState("Overview");const [files,setFiles]=useState<FileList|null>(null);const [msg,setMsg]=useState("");const router=useRouter();
async function upload(){if(!files?.length)return;setMsg("Uploading…");const sb=supabaseBrowser();for(const file of Array.from(files)){const ext=file.name.split(".").pop();const path=`${user.id}/${crypto.randomUUID()}.${ext}`;const bucket=file.type.startsWith("video/")?"videos":"photos";const {error}=await sb.storage.from(bucket).upload(path,file,{upsert:false,contentType:file.type});if(error){setMsg(error.message);return}const {data}=sb.storage.from(bucket).getPublicUrl(path);await sb.from("media").insert({owner_id:user.id,media_type:file.type.startsWith("video/")?"video":"image",storage_path:path,public_url:data.publicUrl,title:file.name,is_public:true});}setMsg("Upload complete.");router.refresh()}
async function signout(){await supabaseBrowser().auth.signOut();router.push("/login")}
return <main className="dashboard"><aside className="sidebar"><a className="logo" href="/">MAYA<span>.</span></a><nav>{["Overview","Media","Bookings","Profile"].map(x=><button key={x} className={tab===x?"active":""} onClick={()=>setTab(x)}>{x}</button>)}</nav><button className="back" onClick={signout}>Sign out</button></aside>
<section className="dashMain"><header className="dashHeader"><div><p className="eyebrow dark">MODEL DASHBOARD</p><h1>{tab}</h1></div>{tab==="Media"&&<label className="button darkButton">+ Upload<input hidden type="file" multiple accept="image/*,video/*" onChange={e=>{setFiles(e.target.files);}}/></label>}</header>
{tab==="Overview"&&<><div className="cards"><div className="dashCard"><span>Photos</span><strong>{media.filter((m:any)=>m.media_type==="image").length}</strong><p>Published media</p></div><div className="dashCard"><span>Videos</span><strong>{media.filter((m:any)=>m.media_type==="video").length}</strong><p>Uploaded videos</p></div><div className="dashCard"><span>Bookings</span><strong>{bookings.length}</strong><p>Client inquiries</p></div><div className="dashCard"><span>Profile</span><strong>{profile?"✓":"!"}</strong><p>Profile status</p></div></div><div className="panel"><h3>Quick upload</h3><p className="muted">Choose photos or videos, then upload them to the secure storage bucket.</p><input type="file" multiple accept="image/*,video/*" onChange={e=>setFiles(e.target.files)}/><button className="button darkButton" onClick={upload}>Upload selected</button><p>{msg}</p></div></>}
{tab==="Media"&&<><div className="panel"><input type="file" multiple accept="image/*,video/*" onChange={e=>setFiles(e.target.files)}/><button className="button darkButton" onClick={upload}>Upload selected</button><p>{msg}</p></div><div className="mediaGrid">{media.map((m:any)=><div className="mediaItem" key={m.id}>{m.media_type==="video"?<video src={m.public_url} controls/>:<img src={m.public_url} alt={m.alt_text||m.title||""}/>}<span>{m.title}</span></div>)}</div></>}
{tab==="Bookings"&&<div className="panel"><h3>Booking inquiries</h3>{bookings.length?bookings.map((b:any)=><div className="bookingRow" key={b.id}><b>{b.name}</b><span>{b.email}</span><span>{b.project_type}</span><p>{b.details}</p></div>):<p className="muted">No inquiries yet.</p>}</div>}
{tab==="Profile"&&<div className="panel"><h3>Profile</h3><p><b>{profile?.display_name||"Model"}</b></p><p>{profile?.bio||"Add your biography in Supabase."}</p><p className="muted">Profile editing can be connected to the profiles table with the same RLS rules.</p></div>}
</section></main>}